SET default_tablespace = '';
SET default_table_access_method = heap;

-- Table: account
CREATE TABLE public.account (
    id integer NOT NULL,
    address text,
    birth_date date,
    email character varying(100) NOT NULL,
    full_name character varying(100) NOT NULL,
    gender character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(15),
    username character varying(50) NOT NULL,
    role_id integer NOT NULL
);
ALTER TABLE public.account OWNER TO postgres;

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: assignment
CREATE TABLE public.assignment (
    id integer NOT NULL,
    academic_year character varying(9) NOT NULL,
    role character varying(255) NOT NULL,
    semester integer,
    class_id integer,
    subject_id integer,
    teacher_id character varying(10) NOT NULL
);
ALTER TABLE public.assignment OWNER TO postgres;

ALTER TABLE public.assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: behavior
CREATE TABLE public.behavior (
    id integer NOT NULL,
    academic_year character varying(9) NOT NULL,
    behavior_score integer,
    semester integer NOT NULL,
    status character varying(50),
    student_id character varying(10) NOT NULL
);
ALTER TABLE public.behavior OWNER TO postgres;

ALTER TABLE public.behavior ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.behavior_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: board_of_directors
CREATE TABLE public.board_of_directors (
    id character varying(10) NOT NULL,
    "position" character varying(255),
    account_id integer NOT NULL
);
ALTER TABLE public.board_of_directors OWNER TO postgres;

-- Table: cashier
CREATE TABLE public.cashier (
    id character varying(10) NOT NULL,
    status character varying(255) NOT NULL,
    account_id integer NOT NULL
);
ALTER TABLE public.cashier OWNER TO postgres;

-- Table: class
CREATE TABLE public.class (
    id integer NOT NULL,
    class_name character varying(255) NOT NULL
);
ALTER TABLE public.class OWNER TO postgres;

ALTER TABLE public.class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: invoice
CREATE TABLE public.invoice (
    id integer NOT NULL,
    academic_year character varying(9),
    outstanding_amount real,
    paid_amount real,
    status character varying(20),
    total_fee real,
    student_id character varying(10)
);
ALTER TABLE public.invoice OWNER TO postgres;

ALTER TABLE public.invoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: parameter
CREATE TABLE public.parameter (
    id integer NOT NULL,
    parameter_name character varying(50) NOT NULL,
    value real NOT NULL
);
ALTER TABLE public.parameter OWNER TO postgres;

ALTER TABLE public.parameter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parameter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: payment_receipt
CREATE TABLE public.payment_receipt (
    id integer NOT NULL,
    paid_amount real,
    payment_date date,
    cashier_id character varying(10) NOT NULL,
    invoice_id integer NOT NULL
);
ALTER TABLE public.payment_receipt OWNER TO postgres;

ALTER TABLE public.payment_receipt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_receipt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: role
CREATE TABLE public.role (
    id integer NOT NULL,
    role_name character varying(50) NOT NULL
);
ALTER TABLE public.role OWNER TO postgres;

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: score
CREATE TABLE public.score (
    id integer NOT NULL,
    academic_year character varying(9),
    comments text,
    final_score real,
    score_15m_1 real,
    score_15m_2 real,
    score_1h_1 real,
    score_1h_2 real,
    semester integer,
    student_id character varying(10) NOT NULL,
    subject_id integer NOT NULL,
    teacher_id character varying(10) NOT NULL
);
ALTER TABLE public.score OWNER TO postgres;

ALTER TABLE public.score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: student
CREATE TABLE public.student (
    id character varying(10) NOT NULL,
    birth_place character varying(100),
    ethnicity character varying(50),
    status character varying(20),
    account_id integer NOT NULL
);
ALTER TABLE public.student OWNER TO postgres;

-- Table: student_class
CREATE TABLE public.student_class (
    id integer NOT NULL,
    academic_year character varying(9) NOT NULL,
    class_id integer NOT NULL,
    student_id character varying(10) NOT NULL
);
ALTER TABLE public.student_class OWNER TO postgres;

ALTER TABLE public.student_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: subject
CREATE TABLE public.subject (
    id integer NOT NULL,
    subject_name character varying(255) NOT NULL
);
ALTER TABLE public.subject OWNER TO postgres;

ALTER TABLE public.subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: supervisor
CREATE TABLE public.supervisor (
    id character varying(10) NOT NULL,
    status character varying(255) NOT NULL,
    account_id integer NOT NULL
);
ALTER TABLE public.supervisor OWNER TO postgres;

-- Table: teacher
CREATE TABLE public.teacher (
    id character varying(10) NOT NULL,
    "position" character varying(255),
    status character varying(255),
    account_id integer NOT NULL
);
ALTER TABLE public.teacher OWNER TO postgres;

-- Table: title
CREATE TABLE public.title (
    id integer NOT NULL,
    min_avg_score real,
    min_behavior_score real,
    title_name character varying(100) NOT NULL
);
ALTER TABLE public.title OWNER TO postgres;

ALTER TABLE public.title ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.title_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: violation
CREATE TABLE public.violation (
    id integer NOT NULL,
    academic_year character varying(9),
    semester integer,
    violation_date date,
    class_id integer NOT NULL,
    student_id character varying(10) NOT NULL,
    supervisor_id character varying(10),
    violation_type_id integer
);
ALTER TABLE public.violation OWNER TO postgres;

ALTER TABLE public.violation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.violation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Table: violation_type
CREATE TABLE public.violation_type (
    id integer NOT NULL,
    deducted_points real,
    violation_name character varying(255) NOT NULL
);
ALTER TABLE public.violation_type OWNER TO postgres;

ALTER TABLE public.violation_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.violation_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);